"""Stream (path) construction from MNIST images, for later signature computation.
Three independent methods for turning a 28x28 image into a path:
  - Method A (`make_pixel_order` + `patch_sv_stream`): a time-augmented stream
    of the largest singular value of 3x3 patches, visited in a fixed shared
    pixel order.
  - Method B (`make_reference_lines` + `line_stream`): a set of fixed
    horizontal/vertical reference lines through the image, each sampled into
    a time-augmented [t, intensity] stream via bilinear interpolation.
  - Method C (`make_hilbert_curve` + `hilbert_stream`): a single Hilbert
    space-filling curve through the image, sampled the same way and cut
    into contiguous segments.
"""


import numpy as np
import torch
import torch.nn.functional as F
torch.set_default_dtype(torch.float64)


def time_channel(n: int) -> torch.Tensor:
    """Return the (n,) normalised step index arange(n) / (n - 1), shared by
    every stream method so the time coordinate is generated by identical
    code regardless of which method's stream it's attached to. Returns
    zeros(n) when n <= 1 (avoids division by zero for a length-1 stream).
    """
    if n > 1:
        return torch.arange(n, dtype=torch.get_default_dtype()) / (n - 1)
    return torch.zeros(n, dtype=torch.get_default_dtype())


def make_pixel_order(k: int = 64, seed: int = 0,
                      image_size: int = 28) -> torch.Tensor:
    """Return (k, 2) int64 tensor of (row, col) locations, sampled uniformly without
    replacement from the interior grid [1, image_size-2]^2, in a fixed order determined
     by seed. Raises ValueError if k exceeds the number of interior pixels.
    """
    lo, hi = 1, image_size - 2
    n_side = hi - lo + 1
    n_interior = n_side * n_side
    if k > n_interior:
        raise ValueError(f"k={k} exceeds number of interior pixels ({n_interior})")

    generator = torch.Generator().manual_seed(seed)
    flat_idx = torch.randperm(n_interior, generator=generator)[:k]
    rows = flat_idx // n_side + lo
    cols = flat_idx % n_side + lo
    return torch.stack([rows, cols], dim=1).to(torch.int64)


def patch_sv_stream(images: torch.Tensor, pixel_order: torch.Tensor,
                     mode: str = "top1") -> torch.Tensor:
    """Method A stream construction.
    images: (N, 28, 28) float32
    pixel_order: (K, 2) int64 from make_pixel_order
    returns: (N, K, 2) float32 for mode="top1", columns [t, sigma1],
             with t = arange(K) / (K - 1).
             (N, K, 4) for mode="all3", columns [t, s1, s2, s3], s1 >= s2 >= s3.
    """
    if mode not in ("top1", "all3"):
        raise ValueError(f"unknown mode: {mode!r}")

    n = images.shape[0]
    k = pixel_order.shape[0]
    offsets = torch.tensor([-1, 0, 1], dtype=torch.int64)

    rows = pixel_order[:, 0]  # (K,)
    cols = pixel_order[:, 1]  # (K,)
    row_grid = (rows.view(k, 1) + offsets.view(1, 3)).view(k, 3, 1).expand(k, 3, 3)
    col_grid = (cols.view(k, 1) + offsets.view(1, 3)).view(k, 1, 3).expand(k, 3, 3)

    patches = images[:, row_grid, col_grid]  # (N, K, 3, 3)
    sigma = torch.linalg.svdvals(patches)  # (N, K, 3), descending

    t = time_channel(k).view(1, k).expand(n, k)

    if mode == "top1":
        return torch.stack([t, sigma[..., 0]], dim=-1).to(torch.get_default_dtype())
    return torch.cat([t.unsqueeze(-1), sigma], dim=-1).to(torch.get_default_dtype())


def make_reference_lines(angles_deg: tuple = (0, 90), counts: tuple = (8, 8),
                          points_per_line: int = 32,
                          image_size: int = 28, seed: int = 0) -> torch.Tensor:
    """Fixed horizontal and/or vertical reference lines through the image domain, evenly spaced.
    Returns (sum(counts), points_per_line, 2) continuous (row, col) coordinates. Only angles 0 and 90
    are supported — every point lies in bounds by construction."""
    if len(angles_deg) != len(counts):
        raise ValueError("angles_deg and counts must have the same length")

    along = torch.linspace(0, image_size - 1, points_per_line)
    line_groups = []
    for angle, count in zip(angles_deg, counts):
        if count == 0:
            continue
        angle = angle % 180
        if angle not in (0, 90):
            raise ValueError(
                f"angle {angle} not supported: only 0 (horizontal) and 90 "
                "(vertical) are guaranteed in-bounds without clipping."
            )
        cross = torch.linspace(0, image_size - 1, count)
        if angle == 0:
            rows = cross.view(count, 1).expand(count, points_per_line)
            cols = along.view(1, points_per_line).expand(count, points_per_line)
        else:
            cols = cross.view(count, 1).expand(count, points_per_line)
            rows = along.view(1, points_per_line).expand(count, points_per_line)
        line_groups.append(torch.stack([rows, cols], dim=-1))

    if not line_groups:
        return torch.empty(0, points_per_line, 2, dtype=torch.get_default_dtype())
    return torch.cat(line_groups, dim=0).to(torch.get_default_dtype())


def line_stream(images: torch.Tensor, lines: torch.Tensor) -> torch.Tensor:
    """Method B stream construction.

    images: (N, 28, 28) float32
    lines: (num_lines, points_per_line, 2) float32 from
           `make_reference_lines`, columns [row, col] in continuous
           pixel-index coordinates.
    returns: (N, num_lines, points_per_line, 2) float32, columns
             [t, intensity]. Intensity is read via batched bilinear
             interpolation (`grid_sample`, no Python loop over images);
             t = time_channel(points_per_line), identical for every line and
             every image.
    """
    n, h, w = images.shape
    num_lines, points_per_line, _ = lines.shape

    x_norm = 2 * lines[..., 1] / (w - 1) - 1
    y_norm = 2 * lines[..., 0] / (h - 1) - 1
    grid = torch.stack([x_norm, y_norm], dim=-1)  # (num_lines, points_per_line, 2)
    grid = grid.unsqueeze(0).expand(n, num_lines, points_per_line, 2)

    intensity = F.grid_sample(
        images.unsqueeze(1), grid, mode="bilinear",
        align_corners=True, padding_mode="border",
    ).squeeze(1)  # (N, num_lines, points_per_line)

    t = time_channel(points_per_line).view(1, 1, points_per_line).expand(
        n, num_lines, points_per_line
    )
    return torch.stack([t, intensity], dim=-1).to(torch.get_default_dtype())


HILBERT_ORDER = 5
HILBERT_SIDE = 2 ** HILBERT_ORDER  # 32
IMAGE_SIZE = 28
NUM_SAMPLE_POINTS = 512
NUM_SEGMENTS = 16
POINTS_PER_SEGMENT = NUM_SAMPLE_POINTS // NUM_SEGMENTS  # 32


def _resample_evenly_by_arc_length(coords: np.ndarray, num_points: int) -> np.ndarray:
    """Resamples a polyline to num_points points evenly spaced along its arc length, via cumulative-
    length parameterisation and linear interpolation."""
    deltas = np.diff(coords, axis=0)
    seg_lengths = np.sqrt((deltas ** 2).sum(axis=1))
    cum_length = np.concatenate([[0.0], np.cumsum(seg_lengths)])
    total_length = cum_length[-1]

    target_s = np.linspace(0.0, total_length, num_points)
    x = np.interp(target_s, cum_length, coords[:, 0])
    y = np.interp(target_s, cum_length, coords[:, 1])
    return np.stack([x, y], axis=1)


def _generate_hilbert_curve(order: int) -> np.ndarray:
    """Grid coordinates of an order-N Hilbert curve, visiting every cell exactly once in standard Hilbert order.
    Returns a (4**order, 2) int64 array of (x, y) grid coordinates, 0 <= x, y < 2**order)"""
    n_cells = 4 ** order
    side = 2 ** order
    xy = np.zeros((n_cells, 2), dtype=np.int64)
    for d in range(n_cells):
        t = d
        s = 1
        x = y = 0
        while s < side:
            rx = 1 & (t // 2)
            ry = 1 & (t ^ rx)
            if ry == 0:
                if rx == 1:
                    x = s - 1 - x
                    y = s - 1 - y
                x, y = y, x
            x += s * rx
            y += s * ry
            t //= 4
            s *= 2
        xy[d] = (x, y)
    return xy


def make_hilbert_curve(order: int = HILBERT_ORDER, image_size: int = IMAGE_SIZE,
                        num_points: int = NUM_SAMPLE_POINTS) -> torch.Tensor:
    """A Hilbert curve through the image domain, resampled to num_points points evenly spaced by arc
    length. Fixed and deterministic — no randomness in the construction.
    Returns (num_points, 2) float64 tensor of (row, col) coordinates in continuous pixel-index space."""
    side = 2 ** order
    xy = _generate_hilbert_curve(order)  # (4**order, 2) int, grid coords
    scale = image_size / side
    coords = xy.astype(np.float64) * scale  # (4**order, 2) continuous [row, col]

    out = _resample_evenly_by_arc_length(coords, num_points)
    return torch.from_numpy(out).to(torch.get_default_dtype())


def hilbert_stream(images: torch.Tensor, curve_points: torch.Tensor) -> torch.Tensor:
    """Method C stream construction: samples image intensity along the fixed Hilbert curve via bilinear
    interpolation, then cuts the sequence into NUM_SEGMENTS contiguous segments
    images: (N, 28, 28)
    curve_points: (num_points, 2) [row, col], from make_hilbert_curve.
    returns: (N, num_segments, points_per_segment, 2), columns
             [t, intensity] - t via time_channel per segment. 
             segments kept separate
    """
    n, h, w = images.shape
    num_points = curve_points.shape[0]

    x_norm = 2 * curve_points[:, 1] / (w - 1) - 1
    y_norm = 2 * curve_points[:, 0] / (h - 1) - 1
    grid = torch.stack([x_norm, y_norm], dim=-1)  # (num_points, 2)
    grid = grid.view(1, 1, num_points, 2).expand(n, 1, num_points, 2)

    intensity = F.grid_sample(
        images.unsqueeze(1), grid, mode="bilinear",
        align_corners=True, padding_mode="border",
    ).squeeze(1).squeeze(1)  # (N, num_points)

    num_segments = NUM_SEGMENTS
    points_per_segment = num_points // num_segments
    intensity = intensity.reshape(n, num_segments, points_per_segment)

    t = time_channel(points_per_segment).view(1, 1, points_per_segment).expand(
        n, num_segments, points_per_segment
    )
    return torch.stack([t, intensity], dim=-1).to(torch.get_default_dtype())
