"""Stream (path) construction from MNIST images, for later signature computation.

Two independent methods for turning a 28x28 image into a path (see PLAN.md /
Method_B.md for the full design rationale):
  - Method A (`make_pixel_order` + `patch_sv_stream`): a time-augmented stream
    of the largest singular value of 3x3 patches, visited in a fixed shared
    pixel order.
  - Method B (`make_reference_lines` + `line_stream`): a set of fixed
    horizontal/vertical reference lines through the image, each sampled into
    a time-augmented [t, intensity] stream via bilinear interpolation.

`row_stream` is a superseded draft of Method B (row/column vectors, no
signature-style time augmentation) kept for now but no longer part of the
active plan - see PLAN.md's Checkpoint 3 status note.

No signature computation happens in this module - see `PLAN.md`.
"""

import torch
import torch.nn.functional as F


def time_channel(n: int) -> torch.Tensor:
    """Return the (n,) float32 normalised step index arange(n) / (n - 1),
    shared by every stream method so the time coordinate is generated by
    identical code regardless of which method's stream it's attached to.
    Returns zeros(n) when n <= 1 (avoids division by zero for a length-1
    stream).
    """
    if n > 1:
        return torch.arange(n, dtype=torch.float32) / (n - 1)
    return torch.zeros(n, dtype=torch.float32)


def make_pixel_order(k: int = 64, seed: int = 0,
                      image_size: int = 28) -> torch.Tensor:
    """Return (k, 2) int64 tensor of (row, col) locations, sampled uniformly
    WITHOUT replacement from the interior grid [1, image_size-2]^2, in a fixed
    order determined by seed. Raises ValueError if k exceeds the number of
    interior pixels.
    """
    lo, hi = 1, image_size - 2
    n_side = hi - lo + 1
    n_interior = n_side * n_side
    if k > n_interior:
        raise ValueError(f"k={k} exceeds number of interior pixels ({n_interior})")

    generator = torch.Generator().manual_seed(seed)
    flat_idx = torch.randperm(n_interior, generator=generator)[:k]
    rows = flat_idx // n_side + lo
    cols = flat_idx % n_side + lo
    return torch.stack([rows, cols], dim=1).to(torch.int64)


def patch_sv_stream(images: torch.Tensor, pixel_order: torch.Tensor,
                     mode: str = "top1") -> torch.Tensor:
    """Method A stream construction.

    images: (N, 28, 28) float32
    pixel_order: (K, 2) int64 from make_pixel_order
    returns: (N, K, 2) float32 for mode="top1", columns [t, sigma1],
             with t = arange(K) / (K - 1).
             (N, K, 4) for mode="all3", columns [t, s1, s2, s3], s1 >= s2 >= s3.
    """
    if mode not in ("top1", "all3"):
        raise ValueError(f"unknown mode: {mode!r}")

    n = images.shape[0]
    k = pixel_order.shape[0]
    offsets = torch.tensor([-1, 0, 1], dtype=torch.int64)

    rows = pixel_order[:, 0]  # (K,)
    cols = pixel_order[:, 1]  # (K,)
    row_grid = (rows.view(k, 1) + offsets.view(1, 3)).view(k, 3, 1).expand(k, 3, 3)
    col_grid = (cols.view(k, 1) + offsets.view(1, 3)).view(k, 1, 3).expand(k, 3, 3)

    patches = images[:, row_grid, col_grid]  # (N, K, 3, 3)
    sigma = torch.linalg.svdvals(patches)  # (N, K, 3), descending

    t = time_channel(k).view(1, k).expand(n, k)

    if mode == "top1":
        return torch.stack([t, sigma[..., 0]], dim=-1).to(torch.float32)
    return torch.cat([t.unsqueeze(-1), sigma], dim=-1).to(torch.float32)


def make_reference_lines(angles_deg: tuple = (0, 90), counts: tuple = (8, 8),
                          points_per_line: int = 32,
                          image_size: int = 28, seed: int = 0) -> torch.Tensor:
    """Return (sum(counts), points_per_line, 2) float32 tensor of (row, col)
    continuous sample coordinates for Method B's reference lines.

    `angles_deg[i]` contributes `counts[i]` evenly-spaced parallel lines:
    angle 0 = horizontal (rows evenly spaced across image height via
    `linspace(0, image_size - 1, count)`, each line sampled left to right);
    angle 90 = vertical (columns evenly spaced across image width, each line
    sampled top to bottom). Every point lies in [0, image_size - 1] by
    construction - no clipping needed. Only angles 0 and 90 (mod 180) are
    supported for now; arbitrary angles need clipping logic, deferred to
    Stage 8. `seed` is reserved for future randomized variants - current
    construction is deterministic without it.
    """
    if len(angles_deg) != len(counts):
        raise ValueError("angles_deg and counts must have the same length")

    along = torch.linspace(0, image_size - 1, points_per_line)
    line_groups = []
    for angle, count in zip(angles_deg, counts):
        if count == 0:
            continue
        angle = angle % 180
        if angle not in (0, 90):
            raise ValueError(
                f"angle {angle} not supported: only 0 (horizontal) and 90 "
                "(vertical) are guaranteed in-bounds without clipping."
            )
        cross = torch.linspace(0, image_size - 1, count)
        if angle == 0:
            rows = cross.view(count, 1).expand(count, points_per_line)
            cols = along.view(1, points_per_line).expand(count, points_per_line)
        else:
            cols = cross.view(count, 1).expand(count, points_per_line)
            rows = along.view(1, points_per_line).expand(count, points_per_line)
        line_groups.append(torch.stack([rows, cols], dim=-1))

    if not line_groups:
        return torch.empty(0, points_per_line, 2, dtype=torch.float32)
    return torch.cat(line_groups, dim=0).to(torch.float32)


def line_stream(images: torch.Tensor, lines: torch.Tensor) -> torch.Tensor:
    """Method B stream construction.

    images: (N, 28, 28) float32
    lines: (num_lines, points_per_line, 2) float32 from
           `make_reference_lines`, columns [row, col] in continuous
           pixel-index coordinates.
    returns: (N, num_lines, points_per_line, 2) float32, columns
             [t, intensity]. Intensity is read via batched bilinear
             interpolation (`grid_sample`, no Python loop over images);
             t = time_channel(points_per_line), identical for every line and
             every image. Lines stay separate in this output - see
             Method_B.md's "no cross-line concatenation" note.
    """
    n, h, w = images.shape
    num_lines, points_per_line, _ = lines.shape

    x_norm = 2 * lines[..., 1] / (w - 1) - 1
    y_norm = 2 * lines[..., 0] / (h - 1) - 1
    grid = torch.stack([x_norm, y_norm], dim=-1)  # (num_lines, points_per_line, 2)
    grid = grid.unsqueeze(0).expand(n, num_lines, points_per_line, 2)

    intensity = F.grid_sample(
        images.unsqueeze(1), grid, mode="bilinear",
        align_corners=True, padding_mode="border",
    ).squeeze(1)  # (N, num_lines, points_per_line)

    t = time_channel(points_per_line).view(1, 1, points_per_line).expand(
        n, num_lines, points_per_line
    )
    return torch.stack([t, intensity], dim=-1).to(torch.float32)


def row_stream(images: torch.Tensor, axis: str = "rows") -> torch.Tensor:
    """Superseded draft of Method B - see the module docstring and PLAN.md's
    Checkpoint 3 status note. Kept for now, not part of the active plan.

    images: (N, 28, 28) float32
    returns: (N, 28, 28) float32.
      axis="rows": stream[n, i, :] is row i of image n (top to bottom).
      axis="cols": stream[n, j, :] is column j of image n (left to right).

    Does not mutate `images`; always returns a copy (via `.clone()` for
    axis="rows", via `.transpose(1, 2).contiguous()` for axis="cols", which
    also copies since the transposed view is non-contiguous).
    """
    if axis == "rows":
        return images.clone()
    if axis == "cols":
        return images.transpose(1, 2).contiguous()
    raise ValueError(f"unknown axis: {axis!r}")
